[project]
name = "master-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Kapitan", email = "daniel@kapitan.net" }
]
requires-python = ">=3.14"
dependencies = [
    "playwright>=1.63.0",
    "tara",
]

[project.scripts]
master-library = "master_library:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
tara = { git = "https://github.com/plugin-healthcare/tara" }

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
    "ty>=0.0.82",
]
